/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* creation time: Tue Feb 10 15:13:53 2015 */
/* tdr version: 2.7.3, build at 20141126 */


using System;
using System.Diagnostics;

namespace tsf4g_tdr_csharp
{



public class TdrDebug
{
    public static void tdrTrace()
    {
        StackTrace st = new StackTrace(true);
        for (int i = 1; i < st.FrameCount; i++)
        {
            if (null != st.GetFrame(i).GetFileName())
            {
                Console.WriteLine("TSF4G_TRACE:  " + st.GetFrame(i).ToString());
            }
        }
    }
}

}
