/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 103 */
/* metalib md5sum: ee7e3bf7f3d8b613d72150e79afc7980 */

/* creation time: Mon Jun 26 14:57:04 2017 */
/* tdr version: 2.7.3, build at 20141126 */


namespace conf
{


public class MetaLib
{
    public static int getVersion()
    {
        return 103;
    }

    public static string getName()
    {
        return "conf";
    }

    public static string getMd5Sum()
    {
        return "ee7e3bf7f3d8b613d72150e79afc7980";
    }

    public static string getTdrVersion()
    {
        return "2.7.3, build at 20141126";
    }
}


}
