/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 221 */
/* metalib md5sum: 1e9590e61fb9003ba725cfc0e6ddb0d7 */

/* creation time: Tue Jun 27 14:58:18 2017 */
/* tdr version: 2.7.3, build at 20141126 */


namespace cs
{


public class MetaLib
{
    public static int getVersion()
    {
        return 221;
    }

    public static string getName()
    {
        return "cs";
    }

    public static string getMd5Sum()
    {
        return "1e9590e61fb9003ba725cfc0e6ddb0d7";
    }

    public static string getTdrVersion()
    {
        return "2.7.3, build at 20141126";
    }
}


}
