/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 103 */
/* metalib md5sum: ee7e3bf7f3d8b613d72150e79afc7980 */

/* creation time: Mon Jun 26 14:57:04 2017 */
/* tdr version: 2.7.3, build at 20141126 */


using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using tsf4g_tdr_csharp;

namespace conf
{


public interface tsf4g_csharp_interface
{
    TdrError.ErrorType construct();
    TdrError.ErrorType load(ref byte[] buffer, int size, ref int usedSize , uint cutVer);
    TdrError.ErrorType load(ref TdrReadBuf srcBuf, uint cutVer);
}

public class ResNickname : tsf4g_csharp_interface
{
    /* public members */
    public Int32 iID;
    public byte[] szSurname;
    public byte[] szMaleName;
    public byte[] szFemaleName;

    /* construct methods */
    public ResNickname()
    {
        szSurname = new byte[16];
        szMaleName = new byte[16];
        szFemaleName = new byte[16];
    }

    /* public methods */
    public TdrError.ErrorType construct()
    {
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /*no need to  set defaultvalue */

        return ret;
    }

    public TdrError.ErrorType load(ref byte[] buffer, int size, ref int usedSize , uint cutVer)
    {
        if (null == buffer || 0 == buffer.GetLength(0) || size > buffer.GetLength(0))
        {
#if (DEBUG)
            TdrDebug.tdrTrace();
#endif
            return TdrError.ErrorType.TDR_ERR_INVALID_BUFFER_PARAMETER;
        }

        TdrReadBuf srcBuf = new TdrReadBuf(ref buffer, size);
        TdrError.ErrorType ret = load(ref srcBuf, cutVer);

        usedSize = srcBuf.getUsedSize();

        return ret;
    }

    public TdrError.ErrorType load(ref TdrReadBuf srcBuf, uint cutVer)
    {
        srcBuf.disableEndian();
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /* adjust cutversion */
        if (0 == cutVer || ResNickname.CURRVERSION < cutVer)
        {
            cutVer = ResNickname.CURRVERSION;
        }

        /* check cutversion */
        if (ResNickname.BASEVERSION > cutVer)
        {
#if (DEBUG)
            TdrDebug.tdrTrace();
#endif
            return TdrError.ErrorType.TDR_ERR_CUTVER_TOO_SMALL;
        }

        /* load member: this.iID */
        {
            ret = srcBuf.readInt32(ref this.iID);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* load member: this.szSurname */
        {
            Int32 size4szSurname = 16;
            if (this.szSurname.GetLength(0) < size4szSurname)
            {
                this.szSurname = new byte[LENGTH_szSurname];
            }

            /* load */
            ret = srcBuf.readCString(ref this.szSurname, (int)size4szSurname);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
#if (DEBUG)
                TdrDebug.tdrTrace();
#endif
                return ret;
            }

        }

        /* load member: this.szMaleName */
        {
            Int32 size4szMaleName = 16;
            if (this.szMaleName.GetLength(0) < size4szMaleName)
            {
                this.szMaleName = new byte[LENGTH_szMaleName];
            }

            /* load */
            ret = srcBuf.readCString(ref this.szMaleName, (int)size4szMaleName);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
#if (DEBUG)
                TdrDebug.tdrTrace();
#endif
                return ret;
            }

        }

        /* load member: this.szFemaleName */
        {
            Int32 size4szFemaleName = 16;
            if (this.szFemaleName.GetLength(0) < size4szFemaleName)
            {
                this.szFemaleName = new byte[LENGTH_szFemaleName];
            }

            /* load */
            ret = srcBuf.readCString(ref this.szFemaleName, (int)size4szFemaleName);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
#if (DEBUG)
                TdrDebug.tdrTrace();
#endif
                return ret;
            }

        }

        return ret;
    }

    /* meta version info */
    public static readonly uint BASEVERSION = 1;
    public static readonly uint CURRVERSION = 1;
    /* entry version info */

    /* length of string or wstring */
    public static readonly uint LENGTH_szSurname = 16;
    public static readonly uint LENGTH_szMaleName = 16;
    public static readonly uint LENGTH_szFemaleName = 16;
}
}
