/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 7 */
/* metalib md5sum: cba5061e49b1bf9ffe9eafe9414d50f6 */

/* creation time: Thu Jun 19 17:46:08 2014 */
/* tdr version: 2.6.8, build at 20140425 */


namespace tdir_cs
{


public class MetaLib
{
    public static int getVersion()
    {
        return 7;
    }

    public static string getName()
    {
        return "tdir_cs";
    }

    public static string getMd5Sum()
    {
        return "cba5061e49b1bf9ffe9eafe9414d50f6";
    }

    public static string getTdrVersion()
    {
        return "2.6.8, build at 20140425";
    }
}


}
