/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 7 */
/* metalib md5sum: cba5061e49b1bf9ffe9eafe9414d50f6 */

/* creation time: Thu Jun 19 17:46:08 2014 */
/* tdr version: 2.6.8, build at 20140425 */

namespace tdir_cs
{

public class  tdir_csMacros
{
    public const int TDIR_PLATFORM_MIN_VERSION_CS = 5; // 支持平台化特性的最小协议版本
    public const int TPDU_MAGIC_DIR = 10; // Dir客户端消息magic编码
    public const int MAX_NODE_BUF_LEN = 64000;
    public const int MAX_EXT_NODE_BUF_LEN = 524288;

    /* macros in macrogroup TPDU_CMD */
    public const int TPDU_CMD_NONE = 0;
    public const int TPDU_CMD_Dir = 100; // Dir消息包头选择字

    /* macros in macrogroup TDIR_PACK_FLAG */
    public const int TDIR_PACK_FLAG_FIRST_PACKAGE = 1;
    public const int TDIR_PACK_FLAG_COMPRESS_TREE = 2;
    public const int TDIR_PACK_FLAG_LAST_PACKAGE = 128;

    /* macros in macrogroup TDir_MSG_ID */
    public const int TDir_MSG_GetDirTree_Req = 6001; // 请求目录树所有节点静态数据
    public const int TDir_MSG_GetDirTree_Rsp = 6002; // 返回目录树所有节点静态数据
    public const int TDir_MSG_Reserve = 9999; // 保留值，仅作为与tdir_node.xml 版本同步

    /* macros in macrogroup ISP_CODE */
    public const int ISP_NONE = 0; // 未知
    public const int ISP_CTC = 1; // 电信
    public const int ISP_CNC = 2; // 联通
    public const int ISP_CERNET = 3; // 教育网
    public const int ISP_BJDXT = 4; // 电信通
    public const int ISP_MOBILE = 5; // 移动
    public const int ISP_TIETONG = 6; // 铁通
    public const int ISP_TOPWAY = 7; // 天威
    public const int ISP_UNIVERSITY = 8; // 大学
    public const int ISP_FOUNDERBN = 9; // 方正宽带
    public const int ISP_GWBN = 10; // 长宽
    public const int ISP_PCCW = 11; // 电讯盈科
    public const int ISP_BGCTV = 12; // 歌华有线
    public const int ISP_CTM = 13; // 澳门电讯
    public const int ISP_FTG = 14; // 科盈电讯
    public const int ISP_SMARTONE = 15; // 数码通
    public const int ISP_OCN = 16; // 东方有线
    public const int ISP_NEWWORLDTEL = 17; // 新世界电讯
    public const int ISP_WHARFTT = 18; // 九仓电讯
    public const int ISP_CITYTEL = 19; // 城市电讯
    public const int ISP_ICABLE = 20; // 香港有线
    public const int ISP_CNLINK = 21; // 互联通
    public const int ISP_CITICPACIFIC = 22; // 中信泰富
    public const int ISP_HUTCHISONTEL = 23; // 和记电讯
    public const int ISP_CONSULTLINK = 24; // 咨询联网
    public const int ISP_NOVA = 25; // 南凌
    public const int ISP_PACNET = 26; // 亚太环通
    public const int ISP_NEWNETWORK = 27; // 新网络
    public const int ISP_DYX = 28; // 第一线
    public const int ISP_SUNNYVISION = 29; // 新力讯
    public const int ISP_EVEROKGROUP = 30; // 恒通国际
    public const int ISP_SINGTEL = 31; // 新电
    public const int ISP_QVSP = 32; // 互联优势
    public const int ISP_INFOTECH = 33; // 香港资讯科技
    public const int ISP_CHINATEL = 34; // 中国电信(香港)

    /* macros in macrogroup PROVINCE_CODE */
    public const int PROVINCE_NONE = 0;
    public const int PROVINCE_HEILONGJIANG = 1;
    public const int PROVINCE_JILIN = 2;
    public const int PROVINCE_LIAONING = 3;
    public const int PROVINCE_BEIJING = 4;
    public const int PROVINCE_TIANJING = 5;
    public const int PROVINCE_HEBEI = 6;
    public const int PROVINCE_SHANDONG = 7;
    public const int PROVINCE_SHANXI = 8;
    public const int PROVINCE_HAINAN = 9;
    public const int PROVINCE_SHANGXI = 10;
    public const int PROVINCE_NEIMENGGU = 11;
    public const int PROVINCE_NINGXIA = 12;
    public const int PROVINCE_GANSU = 13;
    public const int PROVINCE_QINGHAI = 14;
    public const int PROVINCE_XINJIANG = 15;
    public const int PROVINCE_XIZANG = 16;
    public const int PROVINCE_SICHUAN = 17;
    public const int PROVINCE_CHONGQING = 18;
    public const int PROVINCE_HUBEI = 19;
    public const int PROVINCE_HENAN = 20;
    public const int PROVINCE_TAIWAN = 21;
    public const int PROVINCE_ANHUI = 22;
    public const int PROVINCE_JIANGSU = 23;
    public const int PROVINCE_SHANGHAI = 24;
    public const int PROVINCE_ZHEJIANG = 25;
    public const int PROVINCE_HUNAN = 26;
    public const int PROVINCE_JIANGXI = 27;
    public const int PROVINCE_FUJIAN = 28;
    public const int PROVINCE_GUIZHOU = 29;
    public const int PROVINCE_YUNAN = 30;
    public const int PROVINCE_GUANGDONG = 31;
    public const int PROVINCE_GUANGXI = 32;
    public const int PROVINCE_HONGKONG = 33;
    public const int PROVINCE_MACAU = 34;

    public const int MAX_URL_LENGTH = 512;
    public const int MAX_NAME_LEN = 64;
    public const int MAX_STRING_VERSION_LEN = 64; // 字符串格式的版本号最大长度（单位为字节）
    public const int MAX_STA_APPATTR_LEN = 256;
    public const int MAX_APPATTR_LEN = 1024;

    /* macros in macrogroup TDirChildType */
    public const int ChildType_Category = 0; // 分类节点
    public const int ChildType_Leaf = 1; // 叶子节点
    public const int ReservedID = 2; // 用于版本号同步调整

    /* macros in macrogroup TDirFlagBitMap */
    public const int Flag_Heavy = 16; // 繁忙
    public const int Flag_Crowed = 32; // 拥挤
    public const int Flag_Fine = 64; // 良好
    public const int Flag_Unavailable = 128; // 维护

    /* macros in macrogroup GameSvr_Status */
    public const int UNAVAILABLE = 0; // 维护
    public const int FINE = 1; // 良好
    public const int HEAVY = 2; // 爆满
    public const int CROWDED = 3; // 拥塞

    /* macros in macrogroup TDRNODE_BOOL */
    public const int TDRNODE_BOOL_FALSE = 0; // false
    public const int TDRNODE_BOOL_TRUE = 1; // true

    public const int MAX_CON_URL_LEN = 512;

    /* macros in macrogroup TDir_ERRCODE */
    public const int TDir_SUCCESS = 0; // 成功
    public const int TDir_FRAMEHEAD_UNPACK_FAIL = 1; // TCONND包头解码失败
    public const int TDir_FRAMEHEAD_PACK_FAIL = 2; // TCONND包头打包失败
    public const int TDir_TBUS_SEND_FAIL = 3; // TBUS发送失败
    public const int TDir_MSG_INVALID = 4; // TBUS发送失败
    public const int TDir_UNKNOWN_SERVICEID = 5; // 未知 serviceID
    public const int TDir_CS_UNPACK_FAIL = 1000; // 解客户端请求包失败
    public const int TDir_CS_PACK_FAIL = 1001; // 打包客户端回应包失败
    public const int TDir_NODE_PACK_FAIL = 1002; // 打包目录节点失败
    public const int TDir_ROUTING_MSG_FAIL = 1003; // 路由消息失败
    public const int TDir_SS_UNPACK_FAIL = 2000; // 解服务器上报消息失败
    public const int TDir_SS_INVALID_REPORTID = 2001; // 服务器上报ID非法
    public const int TDir_SS_INVALID_REPORTDATA = 2002; // 服务器上报数据非法

}

}
